name : github-action-demo1

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  ubuntu-print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Print command
        run: echo Hi! im running within github with ubuntu

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project!!

    windows-print:
      runs-on: windows-latest

      steps:

        - uses: actions/checkout@v3

        - name: printing in windows
          run: echo HI! running in windows
               echo and deployed within github

